//
// Generated file, do not edit! Created by opp_msgtool 6.1 from veins/modules/application/traci/TraCIDemo11pMessage.msg.
//

#ifndef __VEINS_TRACIDEMO11PMESSAGE_M_H
#define __VEINS_TRACIDEMO11PMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0601
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

class TraCIDemo11pMessage;

}  // namespace veins

#include "veins/base/utils/Coord_m.h" // import veins.base.utils.Coord

#include "veins/modules/messages/BaseFrame1609_4_m.h" // import veins.modules.messages.BaseFrame1609_4

#include "veins/base/utils/SimpleAddress_m.h" // import veins.base.utils.SimpleAddress


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/traci/TraCIDemo11pMessage.msg:7</tt> by opp_msgtool.
 * <pre>
 * packet TraCIDemo11pMessage extends BaseFrame1609_4
 * {
 *     string demoData = "";
 *     LAddress::L2Type senderAddress = -1;
 *     int serial = 0;
 * 
 *     // Dataset Fields with Safe Defaults
 *     int Vehicle_ID;
 *     int Frame_ID = 0;
 *     int Total_Frames = 0;
 *     double Global_Time = 0.0;
 *     double Local_X = 0.0;
 *     double Local_Y = 0.0;
 *     double Global_X = 0.0;
 *     double Global_Y = 0.0;
 *     double v_Length = 0.0;
 *     double v_Width = 0.0;
 *     int v_Class = 1;      // Default to Passenger Car
 *     double v_Vel = 0.0;
 *     double v_Acc = 0.0;
 *     string Lane_ID = "";  // Critical: Initialize string to prevent memory traps
 *     int Preceding = -1;
 *     int Following = -1;
 *     double Space_Headway = -1.0;
 *     double Time_Headway = -1.0;
 * }
 * </pre>
 */
class VEINS_API TraCIDemo11pMessage : public ::veins::BaseFrame1609_4
{
  protected:
    ::omnetpp::opp_string demoData = "";
    LAddress::L2Type senderAddress = -1;
    int serial = 0;
    int Vehicle_ID = 0;
    int Frame_ID = 0;
    int Total_Frames = 0;
    double Global_Time = 0.0;
    double Local_X = 0.0;
    double Local_Y = 0.0;
    double Global_X = 0.0;
    double Global_Y = 0.0;
    double v_Length = 0.0;
    double v_Width = 0.0;
    int v_Class = 1;
    double v_Vel = 0.0;
    double v_Acc = 0.0;
    ::omnetpp::opp_string Lane_ID = "";
    int Preceding = -1;
    int Following = -1;
    double Space_Headway = -1.0;
    double Time_Headway = -1.0;

  private:
    void copy(const TraCIDemo11pMessage& other);

  protected:
    bool operator==(const TraCIDemo11pMessage&) = delete;

  public:
    TraCIDemo11pMessage(const char *name=nullptr, short kind=0);
    TraCIDemo11pMessage(const TraCIDemo11pMessage& other);
    virtual ~TraCIDemo11pMessage();
    TraCIDemo11pMessage& operator=(const TraCIDemo11pMessage& other);
    virtual TraCIDemo11pMessage *dup() const override {return new TraCIDemo11pMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getDemoData() const;
    virtual void setDemoData(const char * demoData);

    virtual const LAddress::L2Type& getSenderAddress() const;
    virtual LAddress::L2Type& getSenderAddressForUpdate() { return const_cast<LAddress::L2Type&>(const_cast<TraCIDemo11pMessage*>(this)->getSenderAddress());}
    virtual void setSenderAddress(const LAddress::L2Type& senderAddress);

    virtual int getSerial() const;
    virtual void setSerial(int serial);

    virtual int getVehicle_ID() const;
    virtual void setVehicle_ID(int Vehicle_ID);

    virtual int getFrame_ID() const;
    virtual void setFrame_ID(int Frame_ID);

    virtual int getTotal_Frames() const;
    virtual void setTotal_Frames(int Total_Frames);

    virtual double getGlobal_Time() const;
    virtual void setGlobal_Time(double Global_Time);

    virtual double getLocal_X() const;
    virtual void setLocal_X(double Local_X);

    virtual double getLocal_Y() const;
    virtual void setLocal_Y(double Local_Y);

    virtual double getGlobal_X() const;
    virtual void setGlobal_X(double Global_X);

    virtual double getGlobal_Y() const;
    virtual void setGlobal_Y(double Global_Y);

    virtual double getV_Length() const;
    virtual void setV_Length(double v_Length);

    virtual double getV_Width() const;
    virtual void setV_Width(double v_Width);

    virtual int getV_Class() const;
    virtual void setV_Class(int v_Class);

    virtual double getV_Vel() const;
    virtual void setV_Vel(double v_Vel);

    virtual double getV_Acc() const;
    virtual void setV_Acc(double v_Acc);

    virtual const char * getLane_ID() const;
    virtual void setLane_ID(const char * Lane_ID);

    virtual int getPreceding() const;
    virtual void setPreceding(int Preceding);

    virtual int getFollowing() const;
    virtual void setFollowing(int Following);

    virtual double getSpace_Headway() const;
    virtual void setSpace_Headway(double Space_Headway);

    virtual double getTime_Headway() const;
    virtual void setTime_Headway(double Time_Headway);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const TraCIDemo11pMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, TraCIDemo11pMessage& obj) {obj.parsimUnpack(b);}


}  // namespace veins


namespace omnetpp {

template<> inline veins::TraCIDemo11pMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<veins::TraCIDemo11pMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __VEINS_TRACIDEMO11PMESSAGE_M_H

